### ISSUE TITLE
Interfaces for the data-flow pipeline

### ISSUE THREAD

**Issue by nfeske** [cbe-project/cbe#3] opened 2019-01-10 13:50 UTC
The CBE will contain several modules that form a data pipeline, which will actually rather be a circuit. The data has the form of different types. For example:

**`Request`** represents a client-initiated block operation. It refers to an operation (read/write/sync), a block number, a size (in blocks), and a success indicator. Note that one request can have a rather large size, like "read 1 MiB".

**`Request_tag`** is number that refers on one (among potentially multiple) requests that are currently in flight. The request tags are allocated/freed at the client-facing front end. They are local to the CBE.

**`Primitive`** represents a CBE-internal operation at the granularity of a single block. It refers to an operation (read/write/sync), a block number, a success indicator, and a request tag. The latter is used to correlate the completion of a primitive with its originating request, in order to issue an acknowledgement to the client once all primitives of a request are done.

**`Block_Data`** a block-sized array of bytes.

Let's call each building block of the pipeline "module". Since the CBE resembles the concept of an MMU, I'll use the existing jargon (like page tables, TLB) for illustrative purposes. So we have tangible terminology for our discussion. Examples for modules are:

* A request splitter that takes one client request along with its request tag and generates a burst of primitives.

* A cache that consumes primitives (coming from the client side), buffers the content of a statically configured maximum number of blocks, fills the buffers by generating primitives (towards the physical block device), and evicts buffers whenever needed in an least-recently used fashion. It also offers an interface to inquiry the presence of blocks in the cache. One particularly important instance of such a cache is the TLB which is populated with CBE metadata blocks (aka page tables).

* CBE node parsers for different tree levels, which each consuming a piece of block data and extracting the high level semantics. Imagine a lens on the raw data.

* A MMU that translates a logical block number to a physical block number using the data stored in the TLB and a primitive. Note that this is not a state machine. It only provides methods for querying the precondition for a translation (e.g., to determine whether the all needed blocks of the page-table hierarchy are in the TLB). Given this information, the user of the MMU can issue requests to the TLB.

* A merger that accepts a sequence of primitives, merges the sequence as long as the primitives are consecutive and belong the the same request tag, and generates block requests.

Of course these are just rough examples. However, their interfaces share the same pattern in that they consume requests/primitives and produce requests/primitives. So let us settle on a convention for naming the corresponding interface functions (aka the bus protocol):

**`request_acceptable` / `primitive_acceptable`** takes a request/primitive as argument and returns whether or not the module is ready to consume the request/primitive. The module's state remains unchanged.

**`submit_request` / `submit_primitive`** takes a request/primitive as argument. The contract says that only requests/primitives that have passed the `acceptable` test passed. This function changed the internal state of the module.

**`peek_generated_request` / `peek_generated_primitive`** queries the next pending request/primitive generated by the module. The module's state remains unchanged.

**`take_generated_request` / `take_generated_primitive`** removes the pending request/primitive (the one returned by the `peek` function from the module. This function changes the internal state of the module.

**Comment by m-stein** [comment] 2019-01-11 11:47
Thanks for this detailed picture of your thoughts.
However, there are some points that I don't understand:

1. Primitives carry a tag for determining when the corresponding client request is finished. Must this not also be accomplished for inter-primitive-dependencies? For instance, we have generated 2 MMU Primitives (M1, M2) from an incoming request. For each of them the MMU generates 2 TLB Primitives (M1T1, M1T2, M2T1, M2T2).  And for each of those the TLB generates 1 back-end Request. Then the CBE falls asleep as no further internal progress can be made. When it awakes next, the Requests for M2T1 and M2T2 are finished. Now I would assume that the CBE realizes that it can get rid of M2 but not of M1 so far.

2. How to achieve for a higher level Primitive that all of its preconditions to be finished are met at the same time? For instance, we have an MMU Primitive that needs 8 specific back-end blocks to be present in the TLB. Four of them are already in place but always before the 5th comes in, the handling of another MMU Primitive evicts the first 4 blocks again.

I hope you don't misunderstand this as critizism. Maybe I have just missed a central point of the model that avoids the above mentioned problems by design.

**Comment by nfeske** [comment] 2019-01-11 13:26
The primitives generated for fetching the page tables are mere side effects of the client-originating requests. Primitives internally issued by the CBE should use a special tag, let's call is "MMU". The causality between a client-generated primitive and its side effects - the primitives generated by the MMU for fetching the page tables required for the translation - is not important.

It only matters that the responses of all MMU-generated requests (the block data containing the page tables of the entire hierarchy) eventually end up in the cache.  The MMU will consult the cache for the presence of all page-tables each time it tries to perform the translation. The condition remains false until all dependent requests are fetched. Does this make sense?

A notion of a "higher level primitive" is not needed in my opinion. All that's needed to express the higher-level semantics is a condition in the MMU. Let me try to illustrate the steps:

The CBE receives a request from a client. The splitter will, in turn, turn this request into a number of client-tagged primitives, referring to logical block numbers.

When the CBE asks the MMU for the physical block number on a given logical block number, the MMU responds with "unknown" unless the whole page table hierarchy for translating the logical address A is readily accessible in the cache (TLB). Let's say we have three levels of page tables (PL). The MMU would check the condition "cached(PL1(A)) and cached(PL2(A)) and cached(PL3(A))". Let's assume that PL2 is missing from the cache.

Next, the CBE will ask the MMU how it can be of any help? (via the generated_primitive interface) The MMU answers, "it would be nice of you to load the physical block X into the TLB". The physical block X corresponds to a page table PL2 that is still missing from the TLB (but the exact meaning of X is only known local to the MMU). Now, the CBE would issue the read(X, MMU) primitive to the device, using the special "MMU" tag.

Sometime later - after blocking for I/O for some time - the block driver completes the primitive. The CBE stuffs the received data into the cache. When now the MMU is asked again to perform the translation, it will get a step further. But now, it will find out that PL3 is still missing. Hence the procedure repeats one more time. Finally when all page-table levels are in the cache, the MMU can walk the page-table hierarchy and yield an actual translation (i.e., the physical block number of the original client-generated primitive).

**Comment by senier** [comment] 2019-01-14 14:33
I like the reuse of the MMU/TLB idiom. TBH, I'm a bit skeptical about whether the integrity protection, encryption and generation-handling of the MHT fits in here well, but it's definitely worth discussing.

What I've derived implicitly from you description is that there is an overarching main program (which I think you refer to as "CBE" sometimes) that calls into the modules, but modules do not call each other. Is that true?

I've identified the following modules:

* CBE (the main program)
* Client (interface to block client)
* Splitter (chop client requests into primitives)
* TLB (cache virtual-to-physical translations)
* MMU (walk MHT and request missing meta data)
* Merger (merge consecutive chunks of same request into bigger request)
* Device (interface to block server)

To handle some client request, CBE would do the following:

1. Check client for request (`Client.peek_request()`) and claim it (`R_Client := Client.take_request()`)
2. Check whether splitter is ready (`Splitter.request_acceptable()`) and submit the request (`Splitter.submit_request(R_Client)`) to splitter
3. While splitter has primitives to handle (`Splitter.peek_primitive()`):
   1. Claim primitive (`P_Splitter := Splitter.take_primitive()`)
   2. Translate primitive using TLB (`T := TLB.translate(P_Splitter)`)
   3. While T is *\<unknown\>*:
      1. Request translation by MMU (`T := TLB.translate(P_Splitter)`)
      2. While MMU has requests to handle (R_MMU := `MMU.peek_request()`):
         1. Check whether merger is ready (`Merger.request_acceptable()`) and submit request to Merger (`Merger.submit_request(R_MMU)`
      3. While Merger has requests (`Merger.peek_request()`):
         1. Claim it (`R_Merger := Merger.take_request()`)
         2. Check whether Device is ready (`Device.request_acceptable()`) and send request (`Device.submit_request(R_Merger)`)
      4. While Device has no requests (`!Device.peer_generated_request()`: SLEEP
      5. Get request from Device (`R_Device := Device.take_generated_request()`)
      6. Load data into TLB (`TLB.Load (R_Device)`)
   4. Check whether merger is ready (`Merger.request_acceptable()`) and submit request to Merger (`Merger.submit_request(T)`
   5. Send (analogous to 3.III.c-e)
   6. Magic happens (I guess there should be another Merger module towards the client which submits the client response?)

Sorry for the lengthy description. Is that about right? What I don't see right now, where integrity check and decryption takes place. The MMU is the place to perform validation (and later possibly encryption) of inner nodes of the tree. However, when/where does it get the actual block requested from the device? [When thinking about it, we probably also need a splitter for client responses to translate the merged requests back into 4k blocks expected by the cache].

**Comment by nfeske** [comment] 2019-01-14 14:59
> TBH, I'm a bit skeptical about whether the integrity protection, encryption and generation-handling of the MHT fits in here well, but it's definitely worth discussing.

It probably won't take us that far. For now, it gives us a nice mental model to make the discussion tangible. Once we have completely internalized the design and its patterns, we have built something more complex upon the basic MMU/TLB mechanism, and start to find the MMU/TLB analogy awkward, we can still swap out the terminology. ;-)

> Sorry for the lengthy description. Is that about right?

Your description captures the idea pretty well. Yes.

> What I don't see right now, where integrity check and decryption takes place.

It is out of the picture right now. That said, I see no fundamental contradiction of these features with the general model of the composeable modules.

> However, when/where does it get the actual block requested from the device?

The MMU is actually not interested in the data. Its job is only the translation of logical to physical addresses, not more than that. The actual payload is fetched/checked/encrypted/decrypted by another module that _uses_ the MMU. Such a `Data_Fetcher` would also generate primitives (towards the block driver).

> ... but modules do not call each other.

Modules can be composed of other modules though. So there may be a hierarchy. You are right that "siblings" of this hierarchy must not call each other directly. The inter-module interaction is always mediated by their common parent.

**Comment by m-stein** [comment] 2019-03-14 11:27
I'd like to make a small amendment to the initial interface proposal according to some offline discussions with @senier. The problem is that the current semantics of ``Take_Generated_Primitive`` / ``Take_Generated_Request`` cannot be implemented in SPARK when using variant records for the types ``Primitive``/``Request``. Using variant records for ``Primitive``/``Request`` is desirable as it is the most elegant, if not only way to ensure that members of invalid primitives / requests are never accessed.

The conflict arises from these 3 facts in SPARK:
1) Objects of one variant-record type may have different sizes depending on the value of their discriminant.
2) Procedures cannot have a return value.
3) Functions cannot have side effects.

Let me give an example:
```
package body CBE.Splitter
...
	procedure Take_Generated_Primitive(
		Obj    : in out Object_Type;
		Result :    out Primitive.Object_Type)
	is
		use type Primitive.Index_Type;
	begin

		case Obj.Curr_Req.Valid is
		when False =>
			Result := (Valid => False);
		when True  =>
			Result := (Valid => True, Operation => ... );
			Next_Primitive(Obj);
		end case;

	end Take_Generated_Primitive;
...
```
This would compile but when doing a SPARK prove, we get errors at both lines ``Result := `` like "discriminant check might fail". This is because the program doesn't know the variant of ``Result`` at this point. But even if we would provide this knowledge through, e.g., contracts only one of the two assignments would be allowed because the size of ``Result`` is already fixed when entering the procedure.

Would we be able to have a return value instead of ``Result``, the subprogram could choose the size of the return value according to the internal execution flow. But in order to do so, ``Take_Generated_Primitive`` must be a function which would not allow ``Obj`` to be altered via ``Next_Primitive``.

Thus, the solution most of us agreed on is replacing ``Take_Generated_Primitive`` by a new procedure:
```
	procedure Drop_Generated_Primitive(
		Obj    : in out Object_Type;
		Result :        Primitive.Object_Type);
```
Which essentially does the same as ``Take_Generated_Primitive`` but without return a primitive. The work flow in the CBE loop would then change to something like:
```
...
P := Splitter.Peek_Generated_Primitive;
if Primitive_Can_Be_Processed(P) then
   Splitter.Drop_Generated_Primitive(P);
   Process_Primitive(P);
end if;
...
```
This can be applied to ``Take_Generated_Primitive`` and ``Take_Generated_Request`` of all modules.

**Comment by m-stein** [comment] 2019-04-01 14:06
I've tried to make use of variant records again by solving the above mentioned conflict as described. However, in the end, our test is successful again but it prints out thousands of warnings and is therefore much much slower:
```
[init -> spark_cbe] Warning: Get_Jmpbuf_Address_Soft not implemented
[init -> spark_cbe] Warning: Set_Jmpbuf_Address_Soft not implemented
```
I'm pretty sure the warnings occur when calling a function with a variant-record return type and directly putting the result into another function/procedure. If I keep the above mentioned approach and merely remove the variant records again, the warnings disappear. So, this is what I do for now because I think translating further modules is more important.

**Comment by senier** [comment] 2019-04-01 14:37
You can disregard this warning. What version of the runtime are you using? This was fixed in https://github.com/Componolit/ada-runtime/commit/055db4b651b7532cb8b9d902c1666e9cb75958a8 which is part of https://github.com/genodelabs/genode/pull/3225.

**Comment by m-stein** [comment] 2019-04-02 10:49
@senier Thanks for the clarification :-) So, the warnings are irrelevant and I can patch them out (I'm not yet on the above mentioned state).

**Closed as completed** 2020-07-01 08:25 UTC
